spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/epidemic-simulation-db
    username: postgres
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    contexts: prod
