spring:
  application:
    name: epidemic-simulation-backend
  jpa:
    hibernate:
      ddl-auto: validate
  #      ddl-auto: <create | create-drop | update | validate | none>
  liquibase:
    change-log: classpath:db/changelog/master.xml